<template>
  <div>
    <h2>新規委員応募</h2>
    <iframe
      src="https://docs.google.com/forms/d/e/1FAIpQLSeGHqRdQttPHsXAD_Ph4q-_xm112vpDxt7kl5tkHquFruc4yw/viewform?embedded=true"
      width="100%"
      height="1800"
      frameborder="0"
      marginheight="0"
      marginwidth="0"
      >読み込んでいます…</iframe
    >
  </div>
</template>